sudo: required
language: php

php:
- 7.1

git:
  depth: 1

services:
- docker

env:
  global:
  - DOCKER_COMPOSE_VERSION=1.17.1
  matrix:
  - DRUPAL_VERSION=~8.5
  - DRUPAL_VERSION=~8.6@rc
  - DRUPAL_VERSION=8.7.x-dev

matrix:
  allow_failures:
  - env: DRUPAL_VERSION=8.7.x-dev


install:
  - curl -fsSL get.docksal.io | sh
  - fin up
  - fin exec composer require webflo/drupal-core-require-dev:$DRUPAL_VERSION --dev

before_script:
  - fin init

script:
  - fin exec "./vendor/bin/grumphp run"
  - fin exec "php ./vendor/bin/phpunit"

notifications:
  email: false